[package]
name = "mdbook-nix-repl"
version = "0.1.0"
edition = "2024"

[dependencies]
mdbook-preprocessor = "0.5.1"
anyhow = "1"
env_logger = "0.11"
log = "0.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
html-escape = "0.2"
semver = "1"
